name: 3d-github-profile

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-3d-github-profile
    steps:
      - uses: actions/checkout@v3
      - uses: doapply/3d-github-profile@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email action@log4j.codes
          git add -A .
          git commit -m "generated"
          git push
